import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/navigation/AppSidebar";
import { AppSidebarTrigger } from "@/components/navigation/AppSidebarTrigger";
import { TopNavigationMenu } from "@/components/navigation/TopNavigationMenu";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} text-zinc-500 antialiased`}
      >
        <Toaster />
        <SidebarProvider defaultOpen={false}>
          <AppSidebar />
          <div className="flex flex-col">
            <AppSidebarTrigger />
            <div>
              <TopNavigationMenu />
            </div>
            <div className="p-2 w-screen">{children}</div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
